---
- name: retrieve priv validator config
  shell: "cat {{ get_validator_key }}"
  register: validator_key_json
  when: node_type == 'validator'

- name: register the validator json
  set_fact: validator="{{ validator_key_json.stdout | default('null') | from_json }}"

- name: gather all validator jsons
  set_fact: validator_jsons="{{ ansible_play_hosts | map('extract', hostvars, 'validator') | list }}"
  run_once: yes

- name: gather all validators
  set_fact: genesis_validators="{{ ansible_play_hosts | map('extract', hostvars, 'pretty_hostname') | list | zip(validator_jsons) | list }}"
  run_once: yes
