- hosts: unhealthy
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  vars_prompt:
    - name: "path"
      prompt: "the absolute path of the forge data"
      default: "/mnt/forge"
      private: no
  roles:
    - role: forge/show_info
      run_once: true
    - role: forge/push
